---
- name: VECTOR | Ensure vector group
  group:
    name: "{{ vector_group }}"
    system: yes
    state: present

- name: VECTOR | Ensure vector user
  user:
    name: "{{ vector_user }}"
    group: "{{ vector_group }}"
    groups: "{{ vector_groups | default('') }}"
    system: yes
    shell: /usr/sbin/nologin
    createhome: no
    append: True

- name: VECTOR | Ensure skeleton paths
  file:
    dest: "{{ item }}"
    owner: "{{ vector_user }}"
    group: "{{ vector_group }}"
    mode: 0755
    state: directory
  with_items:
    - "{{ vector_skeleton_paths }}"

- name: VECTOR | Check vector version
  command: "{{ vector_exec_name }} --version"
  register: vector_check
  changed_when: false
  ignore_errors: true

- name: VECTOR | Check package manager
  shell: |
    if command -v apt >/dev/null; then echo apt;
    elif command -v dnf >/dev/null; then echo dnf;
    elif command -v yum >/dev/null; then echo yum;
    else echo none; fi
  register: pkg_mgr
  changed_when: false

- name: VECTOR | Install Vector (APT)
  apt:
    deb: "{{ vector_deb_package }}"
  when: 
    - vector_force_reinstall or vector_check is failed or vector_version not in vector_check.stdout
    - pkg_mgr.stdout == "apt"

- name: VECTOR | Install Vector (DNF)
  dnf:
    name: "{{ vector_rpm_package }}"
    state: present
  when: 
    - vector_force_reinstall or vector_check is failed or vector_version not in vector_check.stdout
    - pkg_mgr.stdout == "dnf"

- name: VECTOR | Install Vector (YUM)
  yum:
    name: "{{ vector_rpm_package }}"
    state: present
  when: 
    - vector_force_reinstall or vector_check is failed or vector_version not in vector_check.stdout
    - pkg_mgr.stdout == "yum"

- name: VECTOR | Fail if no package manager is found
  fail:
    msg: "No suitable package manager found (APT, DNF, YUM). Cannot install Vector."
  when: pkg_mgr.stdout == "none"
